attitude_controller:
  k_r:
  - 4.0
  - 4.0
  - 2.0
  omega_max: 6.0
camera:
  cx: 320.0
  cy: 240.0
  fx: 320.0
  fy: 320.0
  height: 480
  mount_pitch_deg: 0.0
  width: 640
position_controller:
  kp:
  - 0.8
  - 0.8
  - 0.8
  v_max: 20.0
position_setpoint:
  p_sp_e:
  - 0.0
  - 0.0
  - 0.0
  yaw_sp: 0.0
rates:
  camera_hz: 30.0
  control_hz: 100.0
  physics_hz: 200.0
  visualization_hz: 10.0
rigid_body:
  params_yaml: configs/hummingbird.yaml
termination:
  hit_radius: 0.05
  t_final: 4.0
uav0:
  p_e:
  - 0.0
  - 0.0
  - 0.0
  q_eb:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  t: 0.0
  v_e:
  - 0.0
  - 0.0
  - 0.0
  w_b:
  - 0.0
  - 0.0
  - 0.0
velocity_controller:
  kp:
  - 1.0
  - 1.0
  - 1.2
visualization:
  auto_axis: false
  colors:
    target_dot:
    - 235
    - 120
    - 82
    target_traj:
    - 252
    - 180
    - 49
    uav_arrow:
    - 204
    - 74
    - 116
    uav_body_left:
    - 22
    - 5
    - 139
    uav_body_right:
    - 98
    - 0
    - 170
    uav_traj:
    - 158
    - 22
    - 157
    - 140
  enable: false
  enable_fov: false
  fov_target_marker_size: 7.0
  map_center:
  - 0.0
  - 0.0
  - 0.0
  map_size:
  - 120.0
  - 80.0
  - 60.0
  ned_axes: true
  realtime: false
  target_marker_size: 6.0
  trail_len: 1000
  uav_visual_scale: 2.0
