# configs/ibvs_ctrl.yaml

rates:
  physics_hz: 1000.0
  control_hz: 200.0
  camera_hz: 30.0
  visualization_hz: 24.0

visualization:
  enable: true
  realtime: true
  enable_fov: true
  trail_len: 200
  auto_axis: false
  ned_axes: true
  uav_visual_scale: 3.0
  target_marker_size: 5.0
  fov_target_diameter_m: 2.0
  map_center: [0.0, 0.0, -50.0]
  map_size: [200.0, 100.0, 100.0]
  colors:
    uav_traj: [158, 22, 157, 140]
    uav_body_left: [22, 5, 139]
    uav_body_right: [98, 0, 170]
    uav_arrow: [204, 74, 116]
    target_traj: [252, 180, 49]
    target_dot: [235, 120, 82]
    fov_target: [181, 35, 4]
    fov_status_no_target: [181, 35, 4]
    fov_status_has_target: [0, 128, 0]
  enable_realtime_animation: false
  enable_offline_animation: true
  save_cache: false

monitor:
  enable: true
  realtime: true
  max_points: null
  step_stride: 10
  title: "IBVS Controller Monitor"
  x_min: 0.0

termination:
  t_final: 30.0
  hit_radius: 2.0

uav0:
  t: 0.0
  p_e: [-80.0, 0.0, 0.0]
  v_e: [0.0, 0.0, 0.0]
  q_eb: [1.0, 0.0, 0.0, 0.0]
  w_b: [0.0, 0.0, 0.0]

tgt0:
  t: 0.0
  p_e: [30.0, 0.0, 0.0]
  v_e: [2.0, 0.0, -6.0]

target:
  accel_e: null

rigid_body:
  params_yaml: "configs/hummingbird.yaml"

camera:
  fx: 320.0
  fy: 320.0
  fov_x_deg: null
  fov_y_deg: null
  cx: 0.0
  cy: 0.0
  width: 640
  height: 480
  use_default_frd_to_camera: true
  mount_pitch_deg: 0.0
  R_cb: null
  t_cb_b: [0.0, 0.0, 0.0]
  noise_std_px: 0.0
  noise_std_range_scale_px: 0.0
  detection_prob: 1.0
  detection_range_decay_m: 0.0
  delay_s: 0.0

controller:
  mass: 0.5
  g: 9.81
  foc: 320.0
  k1: 13.0
  k2: 0.1
  k3: 10
  k4: 0.6
  k5: 0.1
  k6: -0.5
  theta_th: -0.6 # rad
  phi_d: 0.0
  omega_max: 3.0
  thrust_min: 0.0
  thrust_max: 6.0
  cos_theta_min: 0.1

logging:
  enable: false
  run_dir: "runs"
  filename: null
  seed: 0
