# configs/rate_ctrl.yaml

rates:
  physics_hz: 5000.0
  control_hz: 200.0
  camera_hz: 30.0
  visualization_hz: 24.0

visualization:
  enable: true
  realtime: true
  enable_fov: false
  trail_len: 1000
  auto_axis: false
  ned_axes: true
  uav_visual_scale: 1.0
  target_marker_size: 6.0
  fov_target_marker_size: 7.0
  map_center: [0.0, 0.0, 0.0]
  map_size: [20.0, 20.0, 12.0]
  colors:
    uav_traj: [158, 22, 157, 140]
    uav_body_left: [22, 5, 139]
    uav_body_right: [98, 0, 170]
    uav_arrow: [204, 74, 116]
    target_traj: [252, 180, 49]
    target_dot: [235, 120, 82]

monitor:
  enable: true
  realtime: true
  max_points: null
  step_stride: 10
  title: "Rate Controller Monitor"
  x_min: 0.0

uav0:
  t: 0.0
  p_e: [0.0, 0.0, 0.0]
  v_e: [0.0, 0.0, 0.0]
  q_eb: [1.0, 0.0, 0.0, 0.0]
  w_b: [0.0, 0.0, 0.0]

rigid_body:
  params_yaml: "configs/hummingbird.yaml"

logging:
  enable: false
  run_dir: "runs"
  filename: null
  seed: 0
